// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzjVRkvAI5HDzTwASD-JMOTBKOi-Qq9Rk',
    appId: '1:932892851530:web:ad9870305e1b9e7ce215b3',
    messagingSenderId: '932892851530',
    projectId: 'exerciseapp-19621',
    authDomain: 'exerciseapp-19621.firebaseapp.com',
    storageBucket: 'exerciseapp-19621.firebasestorage.app',
    measurementId: 'G-63PS07WV31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj49Nr9RnD2B52LHxVwQd3_oA2xrU4e1g',
    appId: '1:932892851530:android:e726a1a9a555cd44e215b3',
    messagingSenderId: '932892851530',
    projectId: 'exerciseapp-19621',
    storageBucket: 'exerciseapp-19621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVxEvseEkWa_p8pRg7J78h6QpSEmdSFAo',
    appId: '1:932892851530:ios:0f3af3ae6613945fe215b3',
    messagingSenderId: '932892851530',
    projectId: 'exerciseapp-19621',
    storageBucket: 'exerciseapp-19621.firebasestorage.app',
    androidClientId: '932892851530-9t1ooicoc8lddq0am8hh6011uhgi6m8k.apps.googleusercontent.com',
    iosClientId: '932892851530-7n23tc87d1cvjhpeqnokmvlgn8csja8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.exerciseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVxEvseEkWa_p8pRg7J78h6QpSEmdSFAo',
    appId: '1:932892851530:ios:0f3af3ae6613945fe215b3',
    messagingSenderId: '932892851530',
    projectId: 'exerciseapp-19621',
    storageBucket: 'exerciseapp-19621.firebasestorage.app',
    androidClientId: '932892851530-9t1ooicoc8lddq0am8hh6011uhgi6m8k.apps.googleusercontent.com',
    iosClientId: '932892851530-7n23tc87d1cvjhpeqnokmvlgn8csja8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.exerciseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzjVRkvAI5HDzTwASD-JMOTBKOi-Qq9Rk',
    appId: '1:932892851530:web:b14e7904b796bfb5e215b3',
    messagingSenderId: '932892851530',
    projectId: 'exerciseapp-19621',
    authDomain: 'exerciseapp-19621.firebaseapp.com',
    storageBucket: 'exerciseapp-19621.firebasestorage.app',
    measurementId: 'G-J6V9N3LC0V',
  );
}
